### ISSUE TITLE
Manual push other users not working

### ISSUE THREAD

**Issue by saitoh183** [trakt/Plex-Trakt-Scrobbler#210]
I can't get my other user to push or scrobble to trakt. I tried to redo all the credentials but still no luck.The credentials are working because there is scrobbled content under his account on trakt .

Log:http://pastebin.com/1BbaZGYC

![image](https://cloud.githubusercontent.com/assets/1534197/8866108/864f1b3e-3186-11e5-8944-9ac372a0a6f0.png)

**Comment by fuzeman** [comment]
The error displayed in the image is a trakt.tv connection issue, the API starts refusing connections when it's under load.

There is this error present in your log file:
```
Exception raised in callback <bound method WebSocket.on_playing of <plugin.scrobbler.methods.s_websocket.WebSocket object at 0x04D02F90>> for event "websocket.playing" - Traceback (most recent call last):
  File "P:\Data\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\pyemitter.py", line 176, in __call_sync
    callback(*args, **kwargs)
  File "P:\Data\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\scrobbler\methods\s_websocket.py", line 29, in on_playing
    WSessionManager.update(session, info, fetch=True)
  File "P:\Data\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\managers\session\s_websocket.py", line 54, in __call__
    data = self.to_dict(obj, info, fetch)
  File "P:\Data\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\managers\session\s_websocket.py", line 121, in to_dict
    filtered_exception=True
  File "P:\Data\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\managers\user.py", line 58, in or_create
    filtered_exception=filtered_exception
  File "P:\Data\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\managers\user.py", line 75, in __call__
    match=match
  File "P:\Data\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\managers\user.py", line 102, in to_dict
    result, user
  File "P:\Data\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\managers\user.py", line 135, in match
    result['account'] = cls.account_function(user, rule)
  File "P:\Data\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\managers\user.py", line 156, in account_function
    log.debug('Mapped user %r to account %r', user['title'], plex_account.account_id)
AttributeError: 'NoneType' object has no attribute 'account_id'
```
Which means the scrobbler wasn't able to match watching activity to any account.

I'm guessing this is from a user that doesn't have an account setup? *(unless there is a bug causing this?)*

**Comment by saitoh183** [comment]
There are 2 users. One has his account setup and scrobble works but not manual Sync the other account is just the user name that I can't delete or use  because it is a managed account.

**Comment by fuzeman** [comment]
Could you upload a log after updating to v0.9.10.3-beta, there should be a new ```Unable to match user <username> against any account``` message displayed instead.

Double check the ```<username>``` displayed matches the account configuration.

---------------------------

This has reminded me, using an email address in the plex authentication options probably won't work correctly. Will look into this issue today, hopefully it's a simple fix.

**Comment by saitoh183** [comment]
@fuzeman 

Will post as soon as it is done

**Comment by saitoh183** [comment]
@fuzeman 

Log part 1: http://pastebin.com/R9Cx7a1i
Log part 2: http://pastebin.com/CPHyd2aT

I will post another Log in about 2hr because i think the API was timing out during the logs i just posted because the scan lasted 20secs whereas the first time i did it (but missed the logs), it lasted 3mins

**Comment by saitoh183** [comment]
@fuzeman 
Any news on this?

**Comment by fuzeman** [comment]
The ```Unable to find show by id: <id>``` messages are interesting... this is likely causing a lot of shows to be ignored in syncs.

Looking into another possible cause for this issue now.

**Comment by fuzeman** [comment]
I've fixed a number of multi-user syncing issues on the development branch ([develop.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/archive/develop.zip)), let me know if this fixes your syncing issues.

**Note:**  The new sync "Interval" option *(at http://trakt-for-plex.github.io/configuration)* probably won't work correctly until the official beta release.

**Comment by saitoh183** [comment]
@fuzeman 

Yup it seems to be working now :)...Now all that is left is to wait till you make it possible to add users without the need of there plex  password.

**Comment by fuzeman** [comment]
I'm currently working on PIN authentication *(same authentication method as PHT)*, should be ready for release this weekend :smiley: 

![](http://i.imgur.com/0ch9Ckw.png)
